services:
  - service: vg.no
    expression: "* * * * *"
    url: https://www.vg.no
    okStatusCode: 200
  - service: nas
    expression: "* * * * *"
    url: http://192.168.1.200:5000
    okStatusCode: 200
  - service: "Home Assistant"
    expression: "*/10 * * * *"
    url: http://192.168.1.89:4357
    okStatusCode: 200

healthcheck:
  url: "https://hc-ping.com/2901db24-a7f2-4184-9807-0118a5526ff4"
  expression: "*/10 * * * *"
